<div class="pxl-grass-widget <?php echo esc_attr($settings['grass_scroll_effect']); ?> <?php if ($settings['grass_scroll_effect'] == 'parallax') : ?>pxl-parallax-scroll<?php endif; ?>" <?php if ($settings['grass_scroll_effect'] == 'parallax') : ?>data-parallax='{"<?php echo esc_attr($settings['parallax_scroll_type']); ?>":<?php echo esc_attr($settings['parallax_scroll_value']); ?>}' <?php endif; ?>>
    <div class="pxl-grass">
        <?php if ($settings['grass_style'] == 'style-1'): ?>
            <?php
            $svg_path = get_template_directory() . '/assets/img/pxl-grass.svg';
            if (file_exists($svg_path)) {
                $svg_content = file_get_contents($svg_path);
                $svg_content = preg_replace('/<\?xml.*?\?>/i', '', $svg_content);
                if (preg_match('/<svg[^>]*class=\"/i', $svg_content)) {
                    $svg_content = preg_replace('/<svg([^>]*)class=\"([^\"]*)\"/i', '<svg$1class="$2 pxl-grass-svg"', $svg_content, 1);
                } else {
                    $svg_content = preg_replace('/<svg\b/i', '<svg class="pxl-grass-svg"', $svg_content, 1);
                }
                echo wp_kses($svg_content, array(
                    'svg' => array(
                        'class' => array(),
                        'id' => array(),
                        'width' => array(),
                        'height' => array(),
                        'viewBox' => array(),
                        'xmlns' => array(),
                        'xmlns:xlink' => array(),
                        'version' => array(),
                        'style' => array(),
                        'preserveAspectRatio' => array(),
                    ),
                    'path' => array(
                        'd' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'stroke-linejoin' => array(),
                        'fill-rule' => array(),
                        'clip-rule' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'g' => array(
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                        'transform' => array(),
                    ),
                    'circle' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'rect' => array(
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'line' => array(
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polygon' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polyline' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'ellipse' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'defs' => array(),
                    'use' => array(
                        'href' => array(),
                        'xlink:href' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'mask' => array(
                        'id' => array(),
                        'maskUnits' => array(),
                        'maskContentUnits' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                    ),
                    'clipPath' => array(
                        'id' => array(),
                        'clipPathUnits' => array(),
                    ),
                    'linearGradient' => array(
                        'id' => array(),
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'radialGradient' => array(
                        'id' => array(),
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fx' => array(),
                        'fy' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'stop' => array(
                        'offset' => array(),
                        'stop-color' => array(),
                        'stop-opacity' => array(),
                        'style' => array(),
                    ),
                ));
            }
            ?>
        <?php endif; ?>
        <?php if ($settings['grass_style'] == 'style-2'): ?>
            <?php
            $svg_path = get_template_directory() . '/assets/img/grass4.svg';
            if (file_exists($svg_path)) {
                $svg_content = file_get_contents($svg_path);
                $svg_content = preg_replace('/<\?xml.*?\?>/i', '', $svg_content);
                if (preg_match('/<svg[^>]*class=\"/i', $svg_content)) {
                    $svg_content = preg_replace('/<svg([^>]*)class=\"([^\"]*)\"/i', '<svg$1class="$2 pxl-grass-svg"', $svg_content, 1);
                } else {
                    $svg_content = preg_replace('/<svg\b/i', '<svg class="pxl-grass-svg"', $svg_content, 1);
                }
                echo wp_kses($svg_content, array(
                    'svg' => array(
                        'class' => array(),
                        'id' => array(),
                        'width' => array(),
                        'height' => array(),
                        'viewBox' => array(),
                        'xmlns' => array(),
                        'xmlns:xlink' => array(),
                        'version' => array(),
                        'style' => array(),
                        'preserveAspectRatio' => array(),
                    ),
                    'path' => array(
                        'd' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'stroke-linejoin' => array(),
                        'fill-rule' => array(),
                        'clip-rule' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'g' => array(
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                        'transform' => array(),
                    ),
                    'circle' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'rect' => array(
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'line' => array(
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polygon' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polyline' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'ellipse' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'defs' => array(),
                    'use' => array(
                        'href' => array(),
                        'xlink:href' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'mask' => array(
                        'id' => array(),
                        'maskUnits' => array(),
                        'maskContentUnits' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                    ),
                    'clipPath' => array(
                        'id' => array(),
                        'clipPathUnits' => array(),
                    ),
                    'linearGradient' => array(
                        'id' => array(),
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'radialGradient' => array(
                        'id' => array(),
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fx' => array(),
                        'fy' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'stop' => array(
                        'offset' => array(),
                        'stop-color' => array(),
                        'stop-opacity' => array(),
                        'style' => array(),
                    ),
                ));
            }
            ?>
        <?php endif; ?>
        <?php if ($settings['grass_style'] == 'style-3'): ?>
            <?php
            $svg_path = get_template_directory() . '/assets/img/flo-grass.svg';
            if (file_exists($svg_path)) {
                $svg_content = file_get_contents($svg_path);
                $svg_content = preg_replace('/<\?xml.*?\?>/i', '', $svg_content);
                if (preg_match('/<svg[^>]*class=\"/i', $svg_content)) {
                    $svg_content = preg_replace('/<svg([^>]*)class=\"([^\"]*)\"/i', '<svg$1class="$2 pxl-grass-svg"', $svg_content, 1);
                } else {
                    $svg_content = preg_replace('/<svg\b/i', '<svg class="pxl-grass-svg"', $svg_content, 1);
                }
                echo wp_kses($svg_content, array(
                    'svg' => array(
                        'class' => array(),
                        'id' => array(),
                        'width' => array(),
                        'height' => array(),
                        'viewBox' => array(),
                        'xmlns' => array(),
                        'xmlns:xlink' => array(),
                        'version' => array(),
                        'style' => array(),
                        'preserveAspectRatio' => array(),
                    ),
                    'path' => array(
                        'd' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'stroke-linejoin' => array(),
                        'fill-rule' => array(),
                        'clip-rule' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'g' => array(
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                        'transform' => array(),
                    ),
                    'circle' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'rect' => array(
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'line' => array(
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polygon' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polyline' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'ellipse' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'defs' => array(),
                    'use' => array(
                        'href' => array(),
                        'xlink:href' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'mask' => array(
                        'id' => array(),
                        'maskUnits' => array(),
                        'maskContentUnits' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                    ),
                    'clipPath' => array(
                        'id' => array(),
                        'clipPathUnits' => array(),
                    ),
                    'linearGradient' => array(
                        'id' => array(),
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'radialGradient' => array(
                        'id' => array(),
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fx' => array(),
                        'fy' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'stop' => array(
                        'offset' => array(),
                        'stop-color' => array(),
                        'stop-opacity' => array(),
                        'style' => array(),
                    ),
                ));
            }
            ?>
        <?php endif; ?>
        <?php if ($settings['grass_style'] == 'paper'): ?>
            <?php
            $svg_path = get_template_directory() . '/assets/img/paper.svg';
            if (file_exists($svg_path)) {
                $svg_content = file_get_contents($svg_path);
                $svg_content = preg_replace('/<\?xml.*?\?>/i', '', $svg_content);
                if (preg_match('/<svg[^>]*class=\"/i', $svg_content)) {
                    $svg_content = preg_replace('/<svg([^>]*)class=\"([^\"]*)\"/i', '<svg$1class="$2 pxl-grass-svg"', $svg_content, 1);
                } else {
                    $svg_content = preg_replace('/<svg\b/i', '<svg class="pxl-grass-svg"', $svg_content, 1);
                }
                echo wp_kses($svg_content, array(
                    'svg' => array(
                        'class' => array(),
                        'id' => array(),
                        'width' => array(),
                        'height' => array(),
                        'viewBox' => array(),
                        'xmlns' => array(),
                        'xmlns:xlink' => array(),
                        'version' => array(),
                        'style' => array(),
                        'preserveAspectRatio' => array(),
                    ),
                    'path' => array(
                        'd' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'stroke-linejoin' => array(),
                        'fill-rule' => array(),
                        'clip-rule' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'g' => array(
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                        'transform' => array(),
                    ),
                    'circle' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'rect' => array(
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'line' => array(
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'stroke-linecap' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polygon' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'polyline' => array(
                        'points' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'ellipse' => array(
                        'cx' => array(),
                        'cy' => array(),
                        'rx' => array(),
                        'ry' => array(),
                        'fill' => array(),
                        'stroke' => array(),
                        'stroke-width' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'defs' => array(),
                    'use' => array(
                        'href' => array(),
                        'xlink:href' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                        'class' => array(),
                        'id' => array(),
                        'style' => array(),
                    ),
                    'mask' => array(
                        'id' => array(),
                        'maskUnits' => array(),
                        'maskContentUnits' => array(),
                        'x' => array(),
                        'y' => array(),
                        'width' => array(),
                        'height' => array(),
                    ),
                    'clipPath' => array(
                        'id' => array(),
                        'clipPathUnits' => array(),
                    ),
                    'linearGradient' => array(
                        'id' => array(),
                        'x1' => array(),
                        'y1' => array(),
                        'x2' => array(),
                        'y2' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'radialGradient' => array(
                        'id' => array(),
                        'cx' => array(),
                        'cy' => array(),
                        'r' => array(),
                        'fx' => array(),
                        'fy' => array(),
                        'gradientUnits' => array(),
                        'gradientTransform' => array(),
                    ),
                    'stop' => array(
                        'offset' => array(),
                        'stop-color' => array(),
                        'stop-opacity' => array(),
                        'style' => array(),
                    ),
                ));
            }
            ?>
        <?php endif; ?>
    </div>
</div>